### ISSUE TITLE
First Issue

### ISSUE THREAD

**Issue by L-Kunu** [L-Kunu/capstone-project#1]
### Value Proposition
As a User..
I need a page to choose my langue
to able to search effortlessly for a lawyer

### Description
![first sketch](https://user-images.githubusercontent.com/94955879/159949661-8261fa2c-3816-459d-b255-831ee0ef6649.png)

### Acceptance

- [ ] When opened, app will spew a page that says "Hello, chose a language" in different languages
- [ ] After language is chosen, the next page comes up where user can type in their name and search criteria 

### Task

- [ ] Call and if needed, write Bar Association (Anwaltskammer) to enquire about list of lawyers that specialise in immigration and family laws
- [ ] While waiting, create a temporary data base with lawyers in Hamburg and environs 
- [ ] Fetch a language API and infuse it into project
- [ ] Create buttons or a tags for the languages
- [ ] Create a formula for users' input
