### ISSUE TITLE
Map Function

### ISSUE THREAD

**Issue by L-Kunu** [L-Kunu/capstone-project#12]
## Value Proposition

**As a** user,
**I need** a map 
**to be able to** find lawyers close to me

## Description
![Untitled-2022-03-23-2338](https://user-images.githubusercontent.com/94955879/163857623-86652016-7ba1-4dfa-ba3f-80e900f29bf9.png)

## Acceptance Criteria

- [ ] Map shows on the result page with marked places of nearest lawyers to user
- [ ] Map is scrollable and scaleable

## Tasks

(for developers team)

- [ ] Create a  new feature branch 
- [ ] Create a component for map
- [ ] Create storybook for component
- [ ] Create test for component
