### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by L-Kunu** [L-Kunu/capstone-project#13]
## Value Proposition

**As a** user,
**I need** a navigation bar 
**to be able to** navigate easily in the app

## Description

![Untitled-2022-03-23-2338](https://user-images.githubusercontent.com/94955879/163863575-f7c000a8-2121-4bc8-9980-5c16bd710cfc.png)

## Acceptance Criteria

- [ ] There is a navbar at the bottom of the app
- [ ] Navbar shows icons top sections of the app

## Tasks

(for developers team)

- [ ] Create a  new feature branch 
- [ ] Create a component for navigation bar
- [ ] Create storybook for component
- [ ] Create test for component
