### ISSUE TITLE
Language filter

### ISSUE THREAD

**Issue by L-Kunu** [L-Kunu/capstone-project#3]
## Value Proposition

**As a** user,
**I need** to choose my language
**to be able to** find the right lawyer for me

## Description

![Screenshot 2022-03-28 at 12 16 00](https://user-images.githubusercontent.com/94955879/160377508-7bbdae2d-0225-4185-98bd-5a5c847a170a.png)

## Acceptance Criteria

- [ ] There are filter criteria for language to choose from
- [ ] If the user choses a language, then cards with information of lawyers that speak the language are displayed
- [ ] Only one language can be chosen at a time

## Tasks

- [ ] Create a branch
- [ ] Create filter component
- [ ] Create story book for components
- [ ] Create test for components
