### ISSUE TITLE
Specialty filter

### ISSUE THREAD

**Issue by L-Kunu** [L-Kunu/capstone-project#4]
## Value Proposition

**As a** user,
**I need** to choose a language and specialty
**to be able to** find the right lawyer

## Description
![Screenshot 2022-03-28 at 14 26 51](https://user-images.githubusercontent.com/94955879/160397734-d77ddd2b-c5dd-4981-95fd-d6f45aa55c33.png)

## Acceptance Criteria

- [ ] There are language and specialty filters to choose from on one screen (first page) 
- [ ] There is search button on the filter page
- [ ] Search results show on the next page
- [ ] There is back button on the search result page

## Tasks

(for developers team)

- [ ] Create a  new feature branch
- [ ] Create specialty / type of lawyer filter as a component
- [ ] Create search and back buttons as components
- [ ] Create storybook for component
- [ ] Create test for component
