### ISSUE TITLE
Toggle / Show more button

### ISSUE THREAD

**Issue by L-Kunu** [L-Kunu/capstone-project#5]
## Value Proposition

**As a** user,
**I need** more information about the lawyers
**to be able to** find a suitable lawyer and contact them

## Description

![Screenshot 2022-03-28 at 16 06 09](https://user-images.githubusercontent.com/94955879/160416650-2d81df4b-e582-48b9-b9e4-4dda527ade96.png)

## Acceptance Criteria

- [x] There are show more buttons on individual cards with lawyers' information
- [x] If show more button is clicked, more information about lawyer is displayed and the card stretches downward
- [x] There is a back button in form of an arrow in place of show more button
- [x] If arrow button is clicked, information reduces and show more button is seen again

## Tasks

(for developers team)

- [x] Create a  new feature branch
- [x] Create a component for buttons
- [x] Create storybook for component
- [ ] Create test for component
